jobs:

  coverage:

    name: Coverage

    depends-on:
    - type: job
      job: tests-mri
      states: [passed]

    context:

      task-defaults:
        eager-trials: 1
        max-auto-trials: 2
        traits:
          cider-ci_api-access: true
          linux: true
          rbenv: true
          ruby: true

      tasks:
        coverage:

          scripts:

            bundle:
              exclusive-executor-resource: bundler
              body: bundle

            coverage:
              body: bundle exec cider-ci_coverage --upload
              start-when:
              - script: bundle


