executions:

  Tests: 
    default: true
    specification: 
      _cider-ci_include: /.cider-ci/test_spec.yml
    trigger: 
      branch: next

  Coverage: 
    specification: 
      _cider-ci_include: /.cider-ci/coverage_spec.yml


