Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'db/**/*'
    - 'datalayer/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'dev/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'zhdk-integration/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/VariableNumber:
  Exclude:
    - 'spec/**/*'

Lint/EndAlignment:
  AlignWith: variable

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 136

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 140

Metrics/CyclomaticComplexity:
  Max: 10

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 83

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20
  Exclude:
    # NOTE: presenters are long by design, they contain lots of data structures
    - 'app/presenters/presenters/**/*'

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 11

Style/AccessorMethodName:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Cop supports --auto-correct.
Style/Not:
  Enabled: false

# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 7

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: false

# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: false

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

Style/UnlessElse:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 5

# Configuration parameters: Include.
Rails/HasAndBelongsToMany:
  Enabled: false

# Configuration parameters: Include.
Rails/Output:
  Enabled: false

# Configuration parameters: Include.
Rails/ReadWriteAttribute:
  Enabled: false

# Configuration parameters: Include.
Rails/Validation:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/*'

# NEW CONFIG SINCE VERSION > 0.29.1

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/IndentAssignment:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/GlobalVars:
  Exclude:
    - 'lib/madek/user_precaching.rb'

Metrics/ModuleLength:
  Max: 200
  CountComments: false

Style/MultilineArrayBraceLayout:
  Enabled: false

# NOTE: this is a bad joke
Style/FrozenStringLiteralComment:
  Enabled: false

# TODO: these seem rather important, check them out:

Rails/Date:
  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'app/controllers/concerns/media_resources/custom_urls_for_controller/custom_url_id.rb'
    - 'app/controllers/my_controller.rb'
    - 'app/helpers/uuid_helper.rb'
    - 'app/lib/living_styleguide.rb'
    - 'app/presenters/presenters/shared/media_resource/media_resources.rb'
    - 'lib/madek/constants/webapp.rb'
    - 'lib/metadata_extractor.rb'
    - 'spec/features/app/json_responder_spec.rb'
