jobs:

_cider-ci_include:
  - cider-ci/jobs/all_tests.yml
  - cider-ci/jobs/code-checks.yml
  - cider-ci/jobs/coverage.yml
  - cider-ci/jobs/meta.yml
  - cider-ci/jobs/tests_jruby.yml
  - cider-ci/jobs/tests_mri.yml
