#!/usr/bin/env bash
set -exu

# precompiles and ammends assets for the last commit (HEAD)
# without any arguments it does a full reset to always work
# `--no-reset` arg can be given to no to a reset
# (usefull when delivering more than 1 commit, only the first needs reset)

# args
DO_RESET=$(test "${1:-""}" == "--no-reset" || echo 1)

# submodules to handle
SUBS="node_modules public/assets"

# sanity check: correct repo?
{
 git config remote.origin.url | grep 'github.com' | grep -q 'Madek/madek-webapp'
} || { echo 'ERROR! wrong repo, go to webapp!' && exit 1 ;}

# get info from current commit:
MSG="$(git log -n1 --format='%s')"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# sanity check: is on a branch?
{ test "$BRANCH" == "master" || test "$BRANCH" == "HEAD"
} && { echo 'ERROR! must be on a branch!' && exit 1 ;}

# clean state for assets/modules
test $DO_RESET && {
  rm -rf public/assets/{bundles,_rails_locales}
  for SUB in $SUBS ; do
    git submodule init "$SUB" || true
    cd "$SUB"
    git reset --hard HEAD
    git clean -fX -fd
    git checkout -B "$BRANCH"
    git fetch
    git reset --hard origin/master
    cd -
  done
}

npm install
./bin/precompile-assets

# commit & push assets/modules
for SUB in $SUBS; do
  cd "$SUB"
  git add --all
  git commit -m "${MSG}" && git push -f -u origin "+HEAD:refs/heads/${BRANCH}" || true
  cd -
done

# ammend assets/modules refs to last commit:
git add $SUBS
git commit --amend --no-edit
