#!/bin/bash

echo "This does a complete reset/setup of the local test environment"
################################################################################
set -exu # be verbose and fail on any error

export RAILS_ENV=test
export DISABLE_DATABASE_ENVIRONMENT_CHECK=1

git submodule update --init --force --quiet

DB_NAME="$(ruby -e 'require "yaml";puts YAML.load_file("config/database.yml")["test"]["database"]')"

bundle exec rake db:pg:terminate_connections db:drop || true # ignore error if not exists yet
bundle exec rake db:create
psql -d "$DB_NAME" -f "datalayer/db/structure.sql"
pg_restore -j4 --data-only -N "public" -d "$DB_NAME" "datalayer/db/personas.pgbin"
bundle exec rake db:migrate

echo ""
echo "Now run a clean test!"
