#!/bin/bash

echo "This does a complete reset/setup of the local dev and test environments"
printf "Waiting 5 seconds";
for N in $(seq 5); do printf '.' && sleep 1; done; echo ""
################################################################################
set -exu # be verbose and fail on any error

rm -rf "$(dirname "$0")/../tmp" &

for ENV in test development; do
  cp ./config/database.yml ./engines/datalayer/config/database.yml
  cd ./engines/datalayer
  RAILS_ENV=$ENV bundle exec rake db:create || true # ignore error
  RAILS_ENV=$ENV bundle exec rake db:pg:terminate_connections
  RAILS_ENV=$ENV ./bin/rerun_personas_migrations
  cd -
done



echo ""
echo "Now run a clean test!"
