#!/bin/sh

echo "This does a complete reset/setup of the local dev and test environments"
echo "If it fails, you most likely have open connections to the db."
echo ""; echo ""; echo ""
sleep 5

set -ex

for ENV in test development; do
  RAILS_ENV=$ENV bundle exec rake db:drop db:create db:migrate
  RAILS_ENV=$ENV ./bin/rerun_personas_migrations
done


echo "Now run a clean test!"
