#!/bin/bash

git submodule update --init spec/_support/test_media

export FILE="spec/_support/test_media/madek_test_media.pgbin"

RAILS_ENV="test" bundle exec rake db:pg:terminate_connections db:drop || true # ignore error if not exists yet
RAILS_ENV="test" bundle exec rake db:create db:pg:structure_and_data:restore FILE="$FILE"
RAILS_ENV="test" bundle exec rake db:migrate db:seed
rm -f "$FILE"
RAILS_ENV="test" bundle exec rake db:pg:structure_and_data:dump FILE="$FILE"
