default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  encoding: unicode
  username: WILL_BE_REPLACED
  password: WILL_BE_REPLACED

test:
  <<: *default
  database: madek_test
