- name: stop madek-webapp
  service:
    name: madek-webapp
    state: stopped
    enabled: false
  failed_when: false

- include_tasks: build.yml
- include_tasks: setup-user.yml
- include_tasks: install-project.yml
- include_tasks: install-ruby.yml
- include_tasks: config.yml
- include_tasks: service.yml
- include_tasks: reverse-proxy.yml
