- name: register ruby version
  shell: |
    set -euo pipefail
    source ~/.asdf/asdf.sh
    cd {{madek_webapp_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{madek_webapp_dir}}"
    executable: /bin/bash
  become: yes
  become_user: "{{madek_webapp_user}}"
  become_method: sudo
  register: madek_webapp_ruby_version

- name: template puma config
  template:
    owner: "{{madek_webapp_user}}"
    src: puma.rb
    dest: '{{madek_webapp_dir}}/config/puma.rb'
    mode: 0644

- template:
    src: madek-webapp.service
    dest: /etc/systemd/system/madek-webapp.service
    mode: 0644
  name: copy  madek-webapp.service

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl

- name: start madek-webapp
  service:
    name: madek-webapp
    enabled: yes
    state: started
