jobs:

  code-checks:

    name: Code-Checks

    description: |
      Run static checks and metrics: complexity, duplication, and format.

    priority: 3

    run-on:
    - type: branch
      include-match: ^.*master.*$

    context:

      task-defaults:
        eager-trials: 1
        max-auto-trials: 2
        traits:
          linux: true
          bash: true

      subcontexts:
        ruby:
          task-defaults:
            traits:
              rbenv: true
              ruby: true
            environment-variables:
              RAILS_ENV: test
              LANG: "en_US.UTF-8"
              RBENV_VERSION: 2.2
            scripts:
              bundle-mri:
                exclusive-executor-resource: bundler_2.2
                body: bundle
              test:
                start-when:
                  - script: bundle-mri

          tasks:

            code_complexity:
              name: 'Ruby: Code complexity with flog'
              scripts:
                test:
                  body: bundle exec cider-ci_flog app/

            code_similarity:
              name: 'Ruby: Code similarity with flay'
              scripts:
                test:
                  body: bundle exec cider-ci_flay app/


            lint_haml:
              name: Lint/Stylecheck with HAML-Lint
              scripts:
                test:
                  body: |
                    #!/bin/sh
                    set -e
                    # lint all view dirs expect styleguide (for now, most components are still auto-converted)
                    find app/views/* -type d -not -path 'app/views/styleguide' -not -path 'app/views/styleguide/**' -exec sh -c 'bundle exec haml-lint {}' \;

            lint_ruby:
              name: 'Ruby: Lint/Stylecheck with Rubocop'
              scripts:
                test:
                  body: bundle exec rubocop



        javascript:
          task-defaults:
            traits:
              nodejs: true
            # en lieu of 'npm install':
            git-options:
              submodules:
                clone: True
                timeout: 60

          tasks:
            lint_coffeescript:
              name: 'JS: Lint/Stylecheck with Coffeelint'
              scripts:
                test:
                  body: |
                    #!/bin/bash
                    set -e
                    for F in app/assets/javascripts/**/*.{coffee,cjsx}; do
                      npm run -s coffeelint -- $F
                    done

        git:
          description: 'Git sanity checks (fixed state)'
          task-defaults:
            max-auto-trials: 1
            traits:
              git: true
          tasks:
            linear_history:
              name: 'Git: Linear History'
              scripts:
                test:
                  body: cider-ci/bin/check-if-linear-history
