jobs:

  code-checks:

    name: Code-Checks

    description: |
      Run static checks and metrics: complexity, duplication, and format.

    priority: 3

    run-on:
    - type: branch
      include-match: ^.+$
      exclude-match: ^(.*no-ci.*)|([a-z]*_wip_.*)$

    context:

      task-defaults:
        git-options:
          submodules:
            clone: true
            timeout: 60
        eager-trials: 1
        max-auto-trials: 2
        traits:
          linux: true
          bash: true

      subcontexts:
        ruby:
          task-defaults:
            traits:
              rbenv: true
              ruby: true
            environment-variables:
              RAILS_ENV: test
              LANG: "en_US.UTF-8"

          tasks:

            code_complexity:
              name: 'Ruby: Code complexity with flog'
              scripts:
                test:
                  body: |
                    #!/usr/bin/env bash
                    set -eux
                    export PATH=$(pwd)/vendor/jruby/bin/:$(ruby -e "puts ENV['PATH'].split(':').reject{|s| s.match(/\.rbenv/)}.join(':')")
                    jruby --dev -S bundle exec cider-ci_flog app/

            code_similarity:
              name: 'Ruby: Code similarity with flay'
              scripts:
                test:
                  body: |
                    #!/usr/bin/env bash
                    set -eux
                    export PATH=$(pwd)/vendor/jruby/bin/:$(ruby -e "puts ENV['PATH'].split(':').reject{|s| s.match(/\.rbenv/)}.join(':')")
                    jruby --dev -S bundle exec cider-ci_flay -m 26 app/

            lint_ruby:
              name: 'Ruby: Lint/Stylecheck with Rubocop'
              #
              # TMP: rubocop from jruby does not work and rbenv+bundler is broken
              #
              # this relies on the following ad-hoc trait:
              #     ssh root@some-executor
              #     gem install rubocop --version=0.39.0 --no-ri --no-rdoc \
              #     && echo '- system_gem_rubocop_v0.39.0' >> /var/local/cider-ci/executor/config/traits.yml
              traits:
                - system_gem_rubocop_v0.39.0
              #
              scripts:
                test:
                  environment-variables:
                    RBENV_VERSION: ''
                  body: /usr/local/bin/rubocop


        javascript:
          task-defaults:
            traits:
              nodejs: true
            # en lieu of 'npm install':
            git-options:
              submodules:
                clone: True
                timeout: 60

          tasks:
            lint_coffeescript:
              name: 'JS: Lint/Stylecheck with `standard` and Coffeelint'
              scripts:
                test:
                  body: npm run lint

        git:
          description: 'Git sanity checks (fixed state)'
          task-defaults:
            max-auto-trials: 1
            traits:
              git: true
          tasks:
            linear_history:
              name: 'Git: Linear History'
              scripts:
                test:
                  body: cider-ci/bin/check-if-linear-history
