jobs:

 feature-tests:
    _cider-ci_include:
      - cider-ci/jobs/feature-tests/feature-tests-base.yml

    name: Feature Tests

    description: |
      This job contains tests involing the whole stack
      of the webapp including front end rendering and
      delivery to a real webbrowser.

    priority: 1

    run-on:
    - type: branch
      include-match: ^.+$
      exclude-match: ^.*no-ci.*$


    depends-on:
    - type: job
      job: tests
      submodule: ['datalayer']
      states: [passed]

    context:

        # TMP: spec rendering (could be extra job but needs same setup as tests!)
        render_specs:
          name: 'Rspec: HTML summary'
          tree-attachments:
            spec_doc:
              content-type: text/html
              include-match: spec_doc\/.*\.html$
          scripts:
            test:
              body: |
                mkdir spec_doc
                ./cider-ci/bin/render-specs.js spec/features > spec_doc/spec-features.html
