jobs:

 feature-tests:

    name: Feature Tests

    priority: 1

    run-on:
    - type: branch
      include-match: ^.*madek-v3.*$

    depends-on:
    - type: job
      job: all_tests
      submodule: ['engines/datalayer']
      states: [passed]

    context:

      name: Feature Tests

      script-defaults:
        environment-variables_process-templates: true
        timeout: 600

      task-defaults:
        eager-trials: 1
        max-auto-trials: 2

        ports:
          XVNC_PORT:
            inet_address: "localhost"
            min: 5900
            max: 5999

        environment-variables:
          RBENV_VERSION: 2.2
          RAILS_ENV: test
          LANG: "en_US.UTF-8"
          DISPLAY: ":{{XVNC_PORT}}"

        git-options:
          submodules:
            clone: True
            timeout: 60

        trial-attachments:
          screenshots:
            glob: tmp/capybara/*.png
            content-type: image/png
          logs:
            glob: 'log/*.log'
            content-type: text/plain
          styleguide_artefacts:
            glob: 'tmp/styleguide-ref.tar.gz'
            content-type: application/x-compressed
          styleguide_hashes_new:
            glob: 'tmp/styleguide-shasums.txt'
            content-type: text/plain
          json_ld_dump:
            glob: 'tmp/ld_dump.json'
            content-type: application/json

        traits:
          firefox-esr: true
          imagemagick: true
          jruby-9000: true
          linux: true
          nodejs: true
          postgresql: true
          rbenv: true
          ruby: true
          tightvnc: true


        scripts:

          _cider-ci_include:
            - cider-ci/jobs/feature-tests/scripts/prepare.yml
            - cider-ci/shared/scripts/manage-database.yml
            - cider-ci/shared/scripts/manage-xvnc.yml
            - cider-ci/jobs/feature-tests/scripts/test.yml

#         # Just one task, used for prototyping and debuging the Cider-CI
#         # project config `cider-ci.yml`
#     tasks:
#       spec/features/my_dashboard_spec.rb:
#        environment-variables:
#          CIDER_CI_TASK_FILE: spec/features/my_dashboard_spec.rb

      tasks:

        "spec/features/styleguide_spec.rb":
          priority: 3

        "json_ld_integration":
          name: 'JSON-LD Dump & Integration'
          environment-variables:
            RAILS_DUMP_LIMIT: 1000
          scripts:
            test:
              body: "bundle exec rails runner ./bin/lodz_dump.rb > ./tmp/ld_dump.json"

        "spec/features/custom_root-url_spec.rb":
          environment-variables:
            RAILS_RELATIVE_URL_ROOT: /my-test

        "spec/features/session/expiration_spec.rb":
          environment-variables:
            RAILS_RELATIVE_URL_ROOT: /my-test
          scripts:
            configure_session_validity_duration:
              body: |
                echo 'madek_session_validity_duration: 10 Seconds' >> config/settings.local.yml
            test:
              start-when:
                configure_session_validity_duration:
                  script: configure_session_validity_duration

      _cider-ci_generate-tasks:
        include-match: spec/features.*_spec.rb



