jobs:

 feature-tests:

    name: Feature Tests

    description: |
      This job contains tests involing the whole stack
      of the webapp including front end rendering and
      delivery to a real webbrowser.

    priority: 1

    run-on:
    - type: branch
      include-match: ^.*master.*$

    depends-on:
    - type: job
      job: tests
      submodule: ['engines/datalayer']
      states: [passed]

    context:

      name: Feature Tests

      script-defaults:
        template-environment-variables: true
        timeout: 600

      task-defaults:

        _cider-ci_include:
          - cider-ci/shared/attachments.yml
          - cider-ci/shared/environment-variables.yml

        eager-trials: 1
        max-auto-trials: 2

        ports:
          XVNC_PORT:
            inet_address: "localhost"
            min: 5900
            max: 5999

        git-options:
          submodules:
            clone: True
            timeout: 60

        traits:
          firefox-esr: true
          imagemagick: true
          jruby-9000: true
          linux: true
          nodejs: true
          postgresql: true
          rbenv: true
          ruby: true
          tightvnc: true


        scripts:

          _cider-ci_include:
            - cider-ci/jobs/feature-tests/scripts/prepare.yml
            - cider-ci/shared/scripts/manage-database.yml
            - cider-ci/shared/scripts/manage-xvnc.yml
            - cider-ci/jobs/feature-tests/scripts/test.yml

#         # Just one task, used for prototyping and debuging the Cider-CI
#         # project config `cider-ci.yml`
#     tasks:
#       spec/features/my_dashboard_spec.rb:
#        environment-variables:
#          CIDER_CI_TASK_FILE: spec/features/my_dashboard_spec.rb

      tasks:
        "spec/features/styleguide_spec.rb":
          scripts:
            test:
              body: echo "disabled till it's faster and/or do we work on CSS."

        "json_ld_integration":
          name: 'JSON-LD Dump & Integration'
          environment-variables:
            RAILS_DUMP_LIMIT: 1000
          scripts:
            test:
              body: "bundle exec rails runner ./bin/lodz_dump.rb > ./tmp/ld_dump.json"

        "spec/features/custom_root-url_spec.rb":
          environment-variables:
            RAILS_RELATIVE_URL_ROOT: /my-test

        "spec/features/session/expiration_spec.rb":
          environment-variables:
            RAILS_RELATIVE_URL_ROOT: /my-test
          scripts:
            configure_session_validity_duration:
              body: |
                echo 'madek_session_validity_duration: 10 Seconds' >> config/settings.local.yml
            test:
              start-when:
                configure_session_validity_duration:
                  script: configure_session_validity_duration


        # TMP: spec rendering (could be extra job but needs same setup as tests!)
        render_specs:
          name: 'Rspec: HTML summary'
          tree-attachments:
            spec_doc:
              content-type: text/html
              include-match: spec_doc\/.*\.html$
          scripts:
            test:
              body: |
                mkdir spec_doc
                ./cider-ci/bin/render-specs.js spec/features > spec_doc/spec-features.html


      _cider-ci_generate-tasks:
        include-match: spec/features.*_spec.rb
