jobs:

  meta:

    name: Meta
    description: |
      Tasks that rely on external (out-of-repository) state.
      Their state is not as fixed as in the other Jobs,
      so it might change over time.

    run-on:
    - type: branch
      include-match: ^.*$
      exclude-match: ^(.*no-ci.*)|([a-z]*_wip_.*)$

    context:
      task-defaults:
        max-auto-trials: 1
        traits:
          linux: true

      tasks:
        git_log:
          scripts:
            main:
              body: "git log -n5"
        git_branch_current:
          name: "git tree contains latest commit from origin/master"
          scripts:
            main:
              body: "cider-ci/bin/check-if-branch-current"
        git_submodules_current:
          name: "git submodules trees all contain latest commit from origin/master"
          scripts:
            main:
              body: "cider-ci/bin/check-if-submodules-current"
        # TODO: automate submodule integration and check here if linear merge possible
        git_submodules_merged:
          name: "git submodules are all merged to origin/master"
          scripts:
            main:
              body: "cider-ci/bin/check-if-submodules-merged"
