jobs:

  tests_mri:

    name: Tests MRI-2.1

    description: |
      Run all specs under MRI 2.1.

    priority: 1

    run-on:
    - type: branch
      include-match: ^.*madek-v3.*$

    depends-on:
    - type: job
      job: tests_mri
      submodule: ['engines/datalayer']
      states: [passed]

    context:
      _cider-ci_include:
        - cider-ci/shared/tests-context.yml

      task-defaults:
        environment-variables:
          RBENV_VERSION: 2.1


