jobs:

  tests_jruby:

    name: Tests JRuby-9000

    description: >
      Run all specs under JRuby 9000.

    run-on:
    - type: branch
      include-match: ^.*madek-v3.*$

    depends-on:
    - type: job
      job: tests_jruby
      submodule: ['engines/datalayer']
      states: [passed]

    context:
      _cider-ci_include:
        - cider-ci/shared/tests-context.yml

      task-defaults:
        environment-variables:
          RBENV_VERSION: 2.1

        scripts:
          test:
            environment-variables:
              RBENV_VERSION: jruby-9000
