jobs:

  unit-tests:

    name: Unit Tests

    priority: 1

    run-on:
    - type: branch
      include-match: ^.*master.*$

    depends-on:
    - type: job
      job: tests
      submodule: ['engines/datalayer']
      states: [passed]

    context:

      name: Unit Tests

      description: |
        This job contains tests involing the ruby runtime
        and possibly the database.


      script-defaults:
        template-environment-variables: true
        timeout: 3 Minutes

      task-defaults:

        _cider-ci_include:
          - cider-ci/shared/attachments.yml
          - cider-ci/shared/environment-variables.yml

        eager-trials: 1
        max-auto-trials: 2

        git-options:
          submodules:
            clone: True
            timeout: 60

        traits:
          imagemagick: true
          linux: true
          nodejs: true
          postgresql: true
          rbenv: true
          ruby: true

        scripts:

          _cider-ci_include:
            - cider-ci/jobs/unit-tests/scripts/prepare.yml
            - cider-ci/shared/scripts/manage-database.yml
            - cider-ci/jobs/unit-tests/scripts/test.yml

      _cider-ci_generate-tasks:
        include-match: spec/.*_spec.rb
        exclude-match: spec/features.*_spec.rb
