jobs:

  unit-tests:
    _cider-ci_include:
      - cider-ci/jobs/unit-tests/unit-tests-base.yml

    name: Unit Tests

    priority: 1

    run-on:
    - type: branch
      include-match: ^.+$
      exclude-match: ^.*no-ci.*$


    depends-on:
    - type: job
      job: tests
      submodule: ['datalayer']
      states: [passed]

    context:
      task-defaults:
        max-auto-trials: 3

      subcontexts:
        ruby:
          tasks:
            assets_manifest:
              name: 'Assets are precompiled and checked in'
              traits: { nodejs: true }
              scripts:
                test:
                  body: |
                    mv public/assets tmp/static_assets
                    bin/precompile-assets
                    cider-ci/bin/check-precompiled-assets tmp/static_assets public/assets
