jobs:
  wip_unit-tests:
    _cider-ci_include:
      - cider-ci/jobs/unit-tests/unit-tests-base.yml

    name: '⟨WIP⟩ Unit Tests'
    description: 'Run Unit Tests in "WIP" mode (i.e. compile assets on the fly)'
    priority: -1337

    run-on:
    - type: branch
      include-match: ^[a-z]*_wip_.*$

    context:
      task-defaults:
        max-auto-trials: 2
        environment-variables:
          MADEK_NO_STATIC_ASSETS: true
